[theme]
primaryColor = "#051C2C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F6F7"
textColor = "#1A1A2E"
font = "sans serif"

[server]
runOnSave = true

[client]
showErrorDetails = false
